
import streamlit as st
from datetime import datetime
import json
import uuid

st.set_page_config(
    page_title="Veridian | Internal Service Agent",
    page_icon="◈",
    layout="wide",
    initial_sidebar_state="expanded",
)

# =========================================================
# SOURCE DATA — ONLY FROM THE ASSIGNMENT DATA PACK
# =========================================================
POLICIES = {
    "KB-01": ("Password Reset", "Employees can reset their own password via the self-service portal at any time. If locked out after 5 failed attempts, contact IT to unlock the account manually. No approval required."),
    "KB-02": ("VPN Access", "VPN access is granted automatically to all full-time employees. Contractors require manager approval submitted via the access request form. VPN credentials expire every 90 days and must be renewed by the employee."),
    "KB-03": ("Laptop Replacement", "Laptops are eligible for replacement after 3 years of service, or earlier in case of verified hardware failure. Requests must be raised at least 2 weeks in advance of intended replacement."),
    "KB-04": ("Software Installation", "Standard software listed in the approved catalog can be self-installed. Non-catalog software requires IT Security review, which takes 3–5 business days."),
    "KB-05": ("Printer Troubleshooting", "For printer issues, first check the printer queue and restart the print spooler. If the issue persists after restart, log a ticket with the printer’s asset tag."),
    "KB-06": ("Email Mailbox Quota", "Default mailbox quota is 25GB. Employees nearing quota should archive old mail. Quota increases beyond 25GB require manager approval and are capped at 50GB."),
    "KB-07": ("Guest Wi-Fi Access", "Guest Wi-Fi credentials are valid for 24 hours and can be generated by any employee from the front-desk kiosk. No IT ticket required."),
    "KB-08": ("Expense Software Access", "Access to the expense management tool is granted by Finance, not IT. IT can only assist with login/technical issues once an account already exists."),
    "KB-09": ("Security Incident Reporting", "Any suspected phishing email, malware, or unauthorized access attempt must be reported to security@veridian-corp.example immediately and should not be forwarded to other employees."),
    "KB-10": ("Work-From-Home Equipment", "Employees working remotely more than 3 days/week are eligible for a one-time home office equipment allowance (chair, monitor). Requires manager sign-off and Finance processing — IT only handles the equipment shipping request once approved."),
    "ASSET": ("Asset Management Policy", "All company-issued hardware, including laptops and monitors, follows a standard 4-year refresh cycle from date of issue. Early replacement outside this cycle requires Finance sign-off in addition to IT approval."),
}

REQUESTS = [
("REQ-01","Aditi Sharma","aditi.sharma@veridian-corp.example","Mon 21 Sep","My laptop won’t turn on at all, it’s completely dead, had it about 3.5 years now.","Not started"),
("REQ-02","Vikram Chawla","vikram.chawla@veridian-corp.example","Mon 21 Sep","Can I get Wi-Fi access for a guest visiting our office tomorrow?","Not started"),
("REQ-03","Karan Mehta","karan.mehta@veridian-corp.example","Mon 21 Sep","I’m locked out of my account, tried my password 6 times.","In progress — reset queued"),
("REQ-04","Ritu Bhatia","ritu.bhatia@veridian-corp.example","Tue 22 Sep","Need approval to install a data-analysis tool that’s not in the software catalog.","Waiting on Security review"),
("REQ-05","Sanjay Oberoi","sanjay.oberoi@veridian-corp.example","Tue 22 Sep","My VPN stopped working this morning, says credentials expired.","Not started"),
("REQ-06","Meera Iyer","meera.iyer@veridian-corp.example","Tue 22 Sep","Printer on the 3rd floor keeps showing “paper jam” even though there’s no jam.","Investigating — technician assigned"),
("REQ-07","Farhan Ali","farhan.ali@veridian-corp.example","Wed 23 Sep","I’ve started working from home 4 days a week, how do I get a monitor?","Not started"),
("REQ-08","Ananya Reddy","ananya.reddy@veridian-corp.example","Wed 23 Sep","I think I got a phishing email asking for my login — forwarding it to a few teammates to check.","Escalated to Security (auto-flagged)"),
("REQ-09","Rohit Desai","rohit.desai@veridian-corp.example","Wed 23 Sep","My mailbox is full and I can’t send emails.","Not started"),
("REQ-10","Kavya Pillai","kavya.pillai@veridian-corp.example","Wed 23 Sep","Can someone give me admin access to the finance reporting server? Need it urgently for month-end.","Not started"),
("REQ-11","Nikhil Bansal","nikhil.bansal@veridian-corp.example","Thu 24 Sep","New contractor joining my team next week, they’ll need VPN access.","Not started"),
("REQ-12","Sneha Kulkarni","sneha.kulkarni@veridian-corp.example","Thu 24 Sep","I can’t log into the expense tool, keeps saying invalid credentials.","Waiting on employee response (asked for a screenshot, no reply yet)"),
("REQ-13","Aman Gupta","aman.gupta@veridian-corp.example","Thu 24 Sep","Laptop screen is flickering on and off, had it 2 years, might just need a fix not a replacement.","Not started"),
("REQ-14","Tanya Chopra","tanya.chopra@veridian-corp.example","Fri 25 Sep","Requesting approval to install a browser extension for productivity tracking.","Not started"),
("REQ-15","Rahul Menon","rahul.menon@veridian-corp.example","Fri 25 Sep","hey can you help, its not working","Not started"),
]

TICKETS = [
("TK-1042","R. Verma","VPN credential expired","Resolved (closed)"),
("TK-1043","S. Iyer","Laptop replacement (3.2 yrs old)","Approved — pending fulfillment (active)"),
("TK-1044","A. Khan","Non-catalog software request","Pending Security review (active)"),
("TK-1045","P. Joshi","Mailbox quota increase","Approved at 35GB (closed)"),
("TK-1046","M. Das","Printer paper jam, floor 2","Resolved (closed)"),
("TK-1047","K. Singh","Home office equipment request","Pending Finance (active)"),
("TK-1048","T. Rao","Phishing email reported","Escalated to Security — under investigation (active)"),
("TK-1049","V. Nambiar","Password reset","Resolved (closed)"),
("TK-1050","J. Fernandes","Admin access request","Rejected — no business justification provided (closed)"),
("TK-1051","L. Menon","Guest Wi-Fi issued","Resolved (closed)"),
]

# =========================================================
# VISUAL SYSTEM
# =========================================================
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Space+Grotesk:wght@500;600;700&display=swap');
html, body, [class*="css"] { font-family: Inter, sans-serif; }
.stApp {
    background: radial-gradient(circle at 82% 0%, rgba(98,78,235,.11), transparent 28%), #080d1b;
    color:#e8edf7;
}
.block-container { max-width:1500px; padding:1rem 2rem 2rem; }
[data-testid="stSidebar"] { background:#0a0f1e; border-right:1px solid #202a40; }
[data-testid="stSidebar"] .block-container { padding:1.2rem 1rem; }
.top {display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #202a40;padding:.1rem 0 1rem;margin-bottom:1rem}
.brand {display:flex;align-items:center;gap:11px}
.logo {width:40px;height:40px;border-radius:11px;background:linear-gradient(135deg,#5c4bea,#765dff);display:flex;align-items:center;justify-content:center;font-size:20px;font-weight:800}
.title {font-family:"Space Grotesk";font-size:18px;font-weight:800}
.sub {font-size:10px;color:#7f8aa3;margin-top:2px}
.live {font-size:10px;color:#a79cff;border:1px solid #332d63;background:#10152c;border-radius:999px;padding:7px 11px;font-weight:800}
.hero {border:1px solid #27334d;border-radius:14px;background:linear-gradient(135deg,#17213a,#11192d);padding:16px 18px;margin-bottom:12px}
.hero h2 {font-family:"Space Grotesk";font-size:21px;margin:0}
.hero p {font-size:11px;color:#8792ab;margin:.3rem 0 0}
.metric {background:#10192d;border:1px solid #26324b;border-radius:12px;padding:10px 13px}
.section {font-size:10px;letter-spacing:.12em;text-transform:uppercase;color:#8995ae;font-weight:800;margin:13px 0 8px}
.card {background:#10192d;border:1px solid #26334d;border-radius:12px;padding:13px}
.trace {background:#050916;border:1px solid #202b43;border-radius:10px;padding:11px 13px;font:11px/1.8 Consolas,monospace;color:#9aa7c0}
.trace b {color:#a698ff}
.answer {background:linear-gradient(135deg,rgba(59,45,125,.4),rgba(16,24,45,.8));border:1px solid #493b91;border-radius:11px;padding:14px}
.answer-label {font-size:9px;color:#a99dff;font-weight:800;letter-spacing:.1em;text-transform:uppercase}
.answer-text {font-size:12px;line-height:1.6;color:#e8ebf5;margin-top:5px}
.source {background:#0c1425;border:1px solid #293650;border-radius:9px;padding:10px 12px;font-size:11px;line-height:1.5;color:#aeb8ca}
.badge {display:inline-block;border-radius:999px;padding:3px 7px;background:#18223a;color:#8e9ab3;font-size:9px;font-weight:700}
.small {font-size:10px;color:#7e8ba5}
.queue-row {background:#10192d;border:1px solid #25324b;border-radius:9px;padding:8px 10px;margin-bottom:6px}
.queue-id {color:#978bff;font:800 9px Consolas}
.queue-name {font-size:11px;font-weight:700}
.queue-issue {font-size:10px;color:#8a96ad;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
[data-testid="stTextInput"] input,[data-testid="stTextArea"] textarea {background:#0b1221!important;border:1px solid #293651!important;color:#edf1f8!important;border-radius:9px!important}
.stButton > button {border-radius:8px;background:#131e35;border:1px solid #2a3854;color:#dce3f2;font-size:10px;font-weight:700}
div.stButton > button[kind="primary"] {background:linear-gradient(135deg,#5a48e0,#6b56ef);border:0;color:white}
[data-testid="stMetric"] {background:#10192d;border:1px solid #26334d;border-radius:12px;padding:7px 11px}
[data-testid="stMetricLabel"] {font-size:10px!important;color:#7f8ba4!important}
[data-testid="stMetricValue"] {font-family:"Space Grotesk";font-size:25px!important}
div[data-baseweb="tab-list"] {gap:4px}
button[data-baseweb="tab"] {font-size:10px;color:#8591a9}
button[data-baseweb="tab"][aria-selected="true"] {color:#a89cff}
</style>
""", unsafe_allow_html=True)

# =========================================================
# AGENT
# =========================================================
def analyze(text):
    t = text.lower().strip()

    if any(x in t for x in ["phishing","malware","unauthorized access","suspicious email"]):
        return dict(intent="Security Incident", source=["KB-09"], decision="ESCALATE", risk="HIGH", confidence="High",
                    answer="Report this to security@veridian-corp.example immediately. Do not forward the suspected phishing email to other employees. This request is being escalated to Security.",
                    next="Security escalation", ticket=True, followup=None)

    if ("password" in t or "account" in t) and any(x in t for x in ["locked","lockout","failed","attempt"]):
        return dict(intent="Password Reset", source=["KB-01"], decision="RESOLVE", risk="LOW", confidence="High",
                    answer="Because you have exceeded 5 failed password attempts, IT must manually unlock the account. No approval is required.",
                    next="IT manual unlock", ticket=True, followup=None)

    if "guest" in t and any(x in t for x in ["wi-fi","wifi","wireless"]):
        return dict(intent="Guest Wi-Fi", source=["KB-07"], decision="RESOLVE", risk="LOW", confidence="High",
                    answer="Guest Wi-Fi credentials are valid for 24 hours and can be generated by any employee from the front-desk kiosk. No IT ticket is required.",
                    next="Use front-desk kiosk", ticket=False, followup=None)

    if "vpn" in t:
        return dict(intent="VPN Access", source=["KB-02"], decision="CLARIFY", risk="LOW", confidence="High",
                    answer="Full-time employees receive VPN access automatically. Contractors require manager approval through the access request form. VPN credentials expire every 90 days and must be renewed by the employee.",
                    next="Confirm employee type", ticket=False,
                    followup="Are you a full-time employee or a contractor?")

    if ("laptop" in t or "notebook" in t) and any(x in t for x in ["dead","won't turn","won’t turn","replacement","flicker"]):
        return dict(intent="Laptop / Hardware", source=["KB-03","ASSET"], decision="ROUTE", risk="MEDIUM", confidence="High",
                    answer="The supplied sources give two relevant rules: KB-03 allows replacement after 3 years or earlier for verified hardware failure, while the Asset Policy states a 4-year refresh cycle and requires Finance sign-off for early replacement. I would route this for hardware verification and the required approval rather than auto-approve it.",
                    next="IT verification + required approval", ticket=True, followup=None)

    if "printer" in t or "paper jam" in t or "spooler" in t:
        return dict(intent="Printer Troubleshooting", source=["KB-05"], decision="GUIDE", risk="LOW", confidence="High",
                    answer="First check the printer queue and restart the print spooler. If the issue persists, log a ticket with the printer’s asset tag.",
                    next="Queue check + spooler restart", ticket=True,
                    followup="If the restart does not help, provide the printer asset tag.")

    if ("home" in t and ("monitor" in t or "equipment" in t)) or "working from home" in t:
        return dict(intent="WFH Equipment", source=["KB-10"], decision="ROUTE", risk="LOW", confidence="High",
                    answer="Employees working remotely more than 3 days/week are eligible for a one-time home-office equipment allowance. Manager sign-off and Finance processing are required; IT handles the shipping request once approved.",
                    next="Manager sign-off → Finance → IT shipping", ticket=True, followup=None)

    if "mailbox" in t or ("email" in t and ("full" in t or "quota" in t)):
        return dict(intent="Mailbox Quota", source=["KB-06"], decision="GUIDE", risk="LOW", confidence="High",
                    answer="The default mailbox quota is 25GB. Archive old mail first. Increases above 25GB require manager approval and are capped at 50GB.",
                    next="Archive old mail / seek approval", ticket=False, followup=None)

    if "expense" in t:
        return dict(intent="Expense Tool", source=["KB-08"], decision="ROUTE", risk="LOW", confidence="Medium",
                    answer="Finance grants access to the expense management tool. IT can assist with login or technical issues once an account already exists.",
                    next="Confirm account exists / route to Finance", ticket=False,
                    followup="Does your Finance account already exist, or are you requesting access for the first time?")

    if "admin access" in t or ("admin" in t and "access" in t):
        return dict(intent="Privileged Access", source=["TK-1050"], decision="ESCALATE", risk="HIGH", confidence="Medium",
                    answer="The supplied policy set does not define an approval procedure for finance-server administrator access. The ticket history contains TK-1050, where an admin access request was rejected because no business justification was provided. I will not grant privileged access and will route this for human review.",
                    next="Human review / access owner", ticket=True, followup=None)

    if any(x in t for x in ["install","software","extension","browser"]):
        return dict(intent="Software Installation", source=["KB-04"], decision="ROUTE", risk="MEDIUM", confidence="High",
                    answer="Standard catalog software can be self-installed. Non-catalog software requires IT Security review, which takes 3–5 business days. The agent cannot approve the exception itself.",
                    next="IT Security review", ticket=True, followup=None)

    return dict(intent="Unclear Request", source=[], decision="CLARIFY", risk="MEDIUM", confidence="Low",
                answer="I do not have enough information to identify the issue safely from the supplied sources. I will not invent a resolution. Please provide the affected system or service and what is not working.",
                next="Await employee details", ticket=False,
                followup="What system or service is affected, and what exactly is not working?")

def record_run(text, employee, email, req_id=None):
    result = analyze(text)
    rec = {
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "request_id": req_id or "CUSTOM",
        "employee": employee,
        "email": email,
        "request": text,
        **result,
        "audit_id": str(uuid.uuid4())[:8],
    }
    st.session_state.audit.insert(0, rec)
    if result["ticket"]:
        st.session_state.created_tickets.insert(0, {
            "id": f"VT-{len(st.session_state.created_tickets)+2001}",
            "employee": employee,
            "intent": result["intent"],
            "status": result["decision"],
        })
    st.session_state.last_result = rec
    return rec

# =========================================================
# STATE
# =========================================================
if "audit" not in st.session_state:
    st.session_state.audit = []
if "created_tickets" not in st.session_state:
    st.session_state.created_tickets = []
if "selected_id" not in st.session_state:
    st.session_state.selected_id = "REQ-01"
if "last_result" not in st.session_state:
    st.session_state.last_result = None
if "employee_override" not in st.session_state:
    st.session_state.employee_override = None

# =========================================================
# HEADER
# =========================================================
st.markdown("""
<div class="top">
 <div class="brand"><div class="logo">◈</div><div><div class="title">VERIDIAN CORP</div><div class="sub">Agentic IT Service Desk · Policy-Grounded Automation</div></div></div>
 <div class="live">◉ AGENT ONLINE · GUARDED MODE</div>
</div>
""", unsafe_allow_html=True)

with st.sidebar:
    st.markdown("## Agent Console")
    st.caption("Veridian internal support environment")
    st.divider()
    st.markdown("**SOURCE PACK**")
    st.write("`11` policies")
    st.write("`15` employee requests")
    st.write("`10` ticket records")
    st.divider()
    st.markdown("**DECISION GUARDRAILS**")
    st.write("🟢 Resolve / guide")
    st.write("🟡 Clarify")
    st.write("🟠 Route")
    st.write("🔴 Escalate")
    st.divider()
    st.success("Source pack loaded")
    st.success("Audit logging active")

# =========================================================
# DASHBOARD
# =========================================================
st.markdown("""
<div class="hero">
<h2>Internal Service Agent</h2>
<p>Understand → ground in supplied sources → decide → act safely → preserve an audit trail</p>
</div>
""", unsafe_allow_html=True)

a,b,c,d = st.columns(4)
a.metric("Policies", "11", "KB + Asset")
b.metric("Requests", "15", "source pack")
c.metric("Tickets", "10", "history")
d.metric("Agent Runs", str(len(st.session_state.audit)), "this session")

# =========================================================
# MAIN WORKSPACE — NO LONG REQUEST WALL
# =========================================================
left, right = st.columns([0.9, 1.45], gap="large")

with left:
    st.markdown('<div class="section">Request Queue</div>', unsafe_allow_html=True)
    labels = {r[0]: f"{r[0]} · {r[1]}" for r in REQUESTS}
    ids = list(labels.keys())
    selected = st.selectbox("Select employee request", ids, index=ids.index(st.session_state.selected_id), format_func=lambda x: labels[x], label_visibility="collapsed")
    st.session_state.selected_id = selected
    rid, name, email, date, issue, status = next(r for r in REQUESTS if r[0] == selected)

    st.markdown(f"""
    <div class="card">
      <div style="display:flex;justify-content:space-between"><span class="queue-id">{rid}</span><span class="badge">{status}</span></div>
      <div style="font-size:14px;font-weight:800;margin-top:6px">{name}</div>
      <div class="small">{email} · {date}</div>
      <div style="font-size:11px;line-height:1.5;color:#aeb8c9;margin-top:10px">{issue}</div>
    </div>
    """, unsafe_allow_html=True)
    st.markdown("<br>", unsafe_allow_html=True)
    if st.button("⚡ Analyze Selected Request", type="primary", use_container_width=True):
        record_run(issue, name, email, rid)
        st.rerun()

    st.markdown("<br>", unsafe_allow_html=True)
    st.caption("Tip: use the request selector to move between all 15 cases without creating a long page.")

with right:
    st.markdown('<div class="section">Agent Playground</div>', unsafe_allow_html=True)
    selected_data = next(r for r in REQUESTS if r[0] == st.session_state.selected_id)
    rid, name, email, date, issue, status = selected_data

    employee = st.text_input("Employee", name)
    employee_email = st.text_input("Email", email)
    message = st.text_area("Employee message", issue, height=80)

    if st.button("Run Agent on This Message", type="primary"):
        record_run(message, employee, employee_email)
        st.rerun()

    result = st.session_state.last_result
    if result:
        st.markdown('<div class="section">Reasoning Trace</div>', unsafe_allow_html=True)
        st.markdown(f"""
        <div class="trace">
        <b>01 INTENT</b> → {result["intent"]}<br>
        <b>02 RETRIEVE</b> → {", ".join(result["source"]) if result["source"] else "No matching source"}<br>
        <b>03 RISK</b> → {result["risk"]} · confidence {result["confidence"]}<br>
        <b>04 DECIDE</b> → {result["decision"]}<br>
        <b>05 NEXT</b> → {result["next"]}<br>
        <b>06 AUDIT</b> → {result["audit_id"]}
        </div>
        """, unsafe_allow_html=True)

        x,y,z = st.columns(3)
        x.metric("Intent", result["intent"])
        y.metric("Decision", result["decision"])
        z.metric("Risk", result["risk"])

        st.markdown('<div class="section">Agent Response</div>', unsafe_allow_html=True)
        st.markdown(f'<div class="answer"><div class="answer-label">Response to employee</div><div class="answer-text">{result["answer"]}</div></div>', unsafe_allow_html=True)
        if result["followup"]:
            st.info("Follow-up: " + result["followup"])

        st.markdown('<div class="section">Grounding</div>', unsafe_allow_html=True)
        if result["source"]:
            for source in result["source"]:
                if source in POLICIES:
                    title, text = POLICIES[source]
                    st.markdown(f'<div class="source"><b>{source} · {title}</b><br>{text}</div><br>', unsafe_allow_html=True)
                else:
                    ticket = next((t for t in TICKETS if t[0] == source), None)
                    if ticket:
                        st.markdown(f'<div class="source"><b>{ticket[0]} · Ticket history</b><br>{ticket[1]} · {ticket[2]} · {ticket[3]}</div><br>', unsafe_allow_html=True)
        else:
            st.markdown('<div class="source"><b>No matching source</b><br>The agent deliberately avoids inventing an answer.</div>', unsafe_allow_html=True)

# =========================================================
# SECONDARY DATA VIEWS
# =========================================================
st.markdown("<br>", unsafe_allow_html=True)
tab1, tab2, tab3, tab4 = st.tabs(["📚 Knowledge Base", "🎫 Ticket Queue", "◌ Audit Trail", "⌘ Architecture"])

with tab1:
    st.markdown("### Knowledge Base")
    st.caption("All supplied policy text is visible here. No external policy is introduced.")
    search = st.text_input("Search policies", placeholder="Search VPN, laptop, security, quota...", key="kbsearch")
    shown = [(k,v) for k,v in POLICIES.items() if not search.strip() or search.lower() in (k+" "+v[0]+" "+v[1]).lower()]
    for code,(title,text) in shown:
        st.markdown(f'<div class="source" style="margin-bottom:8px"><b>{code} · {title}</b><br>{text}</div>', unsafe_allow_html=True)
    st.caption(f"{len(shown)} of {len(POLICIES)} sources shown.")

with tab2:
    st.markdown("### Existing Ticket Queue")
    st.caption("Closed records remain history; active records remain open cases.")
    for tid,emp,summary,status in TICKETS:
        st.markdown(f'<div class="queue-row"><span class="queue-id">{tid}</span> · <b style="font-size:11px">{summary}</b><br><span class="small">{emp} · {status}</span></div>', unsafe_allow_html=True)
    if st.session_state.created_tickets:
        st.markdown("#### Created this session")
        for t in st.session_state.created_tickets:
            st.markdown(f'<div class="queue-row"><b>{t["id"]}</b> · {t["employee"]} · {t["intent"]} · {t["status"]}</div>', unsafe_allow_html=True)

with tab3:
    st.markdown("### Auditable Decision History")
    st.caption("Each execution records the request, source, risk, decision and next action.")
    if not st.session_state.audit:
        st.info("No agent execution yet. Analyze a request above.")
    else:
        for r in st.session_state.audit:
            with st.expander(f'{r["audit_id"]} · {r["request_id"]} · {r["intent"]} · {r["decision"]}'):
                st.json(r)
        st.download_button("Download audit trail JSON", json.dumps(st.session_state.audit, indent=2), "veridian_audit_trail.json", "application/json")

with tab4:
    st.markdown("### Architecture")
    st.code("""Employee request
      ↓
Request understanding
      ↓
Retrieve supplied policy / ticket context
      ↓
Risk + authority guardrails
      ↓
┌───────────────┬────────────┬────────────┐
Resolve / Guide   Clarify      Route       Escalate
└───────────────┴────────────┴────────────┘
                     ↓
               Ticket action
                     ↓
                 Audit trail
""")
    st.markdown("**Core principle:** controlled autonomy. The agent acts only where the supplied source material supports the action and routes uncertain, privileged or security-sensitive cases to a human.")

st.caption("Veridian Corp · AIONOS Assignment 2 · Source-grounded prototype")
